# Generated by Django 4.2.8 on 2024-05-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dongjin_point',
            field=models.FloatField(default=5),
        ),
    ]
